; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Modules
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][version] = "3.0-rc4"

projects[advanced_help][version] = "1.1"

projects[backup_migrate][version] = "2.8"

projects[ctools][version] = "1.4"

projects[facetapi][version] = "1.3"

projects[datatables][version] = "1.1"

projects[devel][version] = "1.4"

projects[entity][version] = "1.3"

projects[entityreference][version] = "1.1"

projects[entityreference_prepopulate][version] = "1.5"

projects[facetapi_bonus][version] = "1.1"

projects[features][version] = "2.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[SHANTI][download][type] = ""
projects[SHANTI][download][url] = ""
projects[SHANTI][type] = "module"
projects[SHANTI][subdir] = "shanti"
projects[SHANTI][version] = "0.1-alpha2"

projects[panels][version] = "3.4"

projects[imagepicker][version] = "1.7"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[lightbox2][version] = "1.0-beta1"

projects[mass_contact][version] = "1.0"

projects[migrate][version] = "2.5"

projects[module_filter][version] = "1.8"

projects[og][version] = "2.5"

projects[services][version] = "3.7"

projects[search_api][version] = "1.11"

projects[search_api_solr][version] = "1.4"

projects[sharethis][version] = "2.5"

projects[shib_auth][version] = "4.0"

projects[superfish][version] = "1.9"

projects[views][version] = "3.7"

projects[webform][version] = "3.20"

projects[webform_conditional][version] = "1.0-beta2"

projects[webform_report][version] = "1.0"

projects[wysiwyg][version] = "2.2"
; add wysiwyg patch: https://www.drupal.org/files/issues/wysiwyg-1757684.28.patch 

projects[zend][version] = "1.0-beta1"

; Modules
projects[sarvaka_modules][type] = "module"
projects[sarvaka_modules][download][type] = "git"
projects[sarvaka_modules][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_modules.git"
projects[sarvaka_modules][download][revision] = "9e898ac03820787215497e7b7c1ba241f852e2c2"

projects[shivanode][type] = "module"
projects[shivanode][download][type] = "git"
projects[shivanode][download][url] = "https://github.com/shanti-uva/drupal_shiva_manager.git"
projects[shivanode][download][branch] = "newtheme"
projects[shivanode][download][revision] = "98d921b17bb1078227f4ea36d10e4aa45344d6c7"

projects[shanti_kmaps_fields][type] = "module"
projects[shanti_kmaps_fields][download][type] = "git"
projects[shanti_kmaps_fields][download][url] = "https://github.com/shanti-uva/drupal_shanti_kmaps_fields.git"
projects[shanti_kmaps_fields][download][revision] = "d3d8ac8864073278962c0c8f1fa8565f23b430ad"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[shantidev][download][type] = ""
projects[shantidev][download][url] = ""
projects[shantidev][type] = "module"

projects[shib_preuser][type] = "module"
projects[shib_preuser][download][type] = "git"
projects[shib_preuser][download][url] = "https://github.com/ThanGrove/shib_preuser"
projects[shib_preuser][download][revision] = "a28d3de757d6ff8431d549ee1d745dae7e7682eb"

; Themes
projects[sarvaka_shiva][type] = "theme"
projects[sarvaka_shiva][download][type] = "git"
projects[sarvaka_shiva][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_shiva.git"
projects[sarvaka_shiva][download][revision] = "dfc1dc74064949c7200d794a8b163a8cbf0b877b"

projects[shanti_sarvaka][type] = "theme"
projects[shanti_sarvaka][download][type] = "git"
projects[shanti_sarvaka][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_theme.git"
projects[shanti_sarvaka][download][revision] = "35b8332bc06c6de0ede18ea2fde010bdb415cd1e"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[dompdf][download][type] = ""
libraries[dompdf][download][url] = ""
libraries[dompdf][directory_name] = "dompdf"
libraries[dompdf][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[google-api-php-client][download][type] = ""
libraries[google-api-php-client][download][url] = ""
libraries[google-api-php-client][directory_name] = "google-api-php-client"
libraries[google-api-php-client][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"


