; This file was auto-generated by drush make for a Shiva Manager Site
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Contrib Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.1"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.8"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.6"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.5"

projects[datatables][subdir] = "contrib"
projects[datatables][version] = "1.2"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[entityreference_prepopulate][subdir] = "contrib"
projects[entityreference_prepopulate][version] = "1.5"

projects[facetapi_bonus][subdir] = "contrib"
projects[facetapi_bonus][version] = "1.1"

projects[features][subdir] = "contrib"
projects[features][version] = "2.3"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.12"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.5"

projects[i18nviews][subdir] = "contrib"
projects[i18nviews][version] = "3.x-dev"

projects[imagepicker][subdir] = "contrib"
projects[imagepicker][version] = "1.8"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.5"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[lightbox2][subdir] = "contrib"
projects[lightbox2][version] = "1.0-beta1"

projects[mass_contact][subdir] = "contrib"
projects[mass_contact][version] = "1.0"

projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.7"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.8"

projects[og][subdir] = "contrib"
projects[og][version] = "2.7"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[services][subdir] = "contrib"
projects[services][version] = "3.11"

projects[search_api][subdir] = "contrib"
projects[search_api][version] = "1.14"

projects[search_api_solr][subdir] = "contrib"
projects[search_api_solr][version] = "1.6"

projects[sharethis][subdir] = "contrib"
projects[sharethis][version] = "2.10"

projects[shib_auth][subdir] = "contrib"
projects[shib_auth][version] = "4.1"

projects[superfish][subdir] = "contrib"
projects[superfish][version] = "1.9"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.10"

projects[watchdog_array][subdir] = "contrib"
projects[watchdog_array][version] = "1.0"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.3"

projects[webform_conditional][subdir] = "contrib"
projects[webform_conditional][version] = "1.0-beta2"

projects[webform_report][subdir] = "contrib"
projects[webform_report][version] = "1.0"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Shanti Modules

projects[sarvaka_modules][type] = "module"
projects[sarvaka_modules][download][type] = "git"
projects[sarvaka_modules][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_modules.git"
projects[shivanode][download][branch] = "master"
projects[sarvaka_modules][subdir] = "shanti"

projects[shivanode][type] = "module"
projects[shivanode][download][type] = "git"
projects[shivanode][download][url] = "https://github.com/shanti-uva/drupal_shiva_manager.git"
projects[shivanode][download][branch] = "newtheme"
projects[shivanode][subdir] = "shanti"

projects[shanti_kmaps_fields][type] = "module"
projects[shanti_kmaps_fields][download][type] = "git"
projects[shanti_kmaps_fields][download][url] = "https://github.com/shanti-uva/drupal_shanti_kmaps_fields.git"
projects[shanti_kmaps_fields][download][branch] = "master"
projects[shanti_kmaps_fields][subdir] = "shanti"

projects[shib_preuser][type] = "module"
projects[shib_preuser][download][type] = "git"
projects[shib_preuser][download][url] = "https://github.com/ThanGrove/shib_preuser"
projects[shib_preuser][download][branch] = "master"
projects[shib_preuser][subdir] = "shanti"

; Old Themes
projects[zen][version] = "3.3"

projects[shantizen][type] = "theme"
projects[shantizen][download][type] = "git"
projects[shantizen][download][url] = "https://github.com/ThanGrove/Shantizen.git"
projects[shantizen][download][revision] = "d34a382a7680ab1fa4aa010832fe4131b89483a0"

; New Saravaka Based Themes
projects[sarvaka_shiva][type] = "theme"
projects[sarvaka_shiva][download][type] = "git"
projects[sarvaka_shiva][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_shiva.git"
projects[sarvaka_shiva][download][branch] = "master"

projects[shanti_sarvaka][type] = "theme"
projects[shanti_sarvaka][download][type] = "git"
projects[shanti_sarvaka][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_theme.git"
projects[shanti_sarvaka][download][branch] = "master"

; Libraries

; Colorbox
libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox.git"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Google Api Client
libraries[google-api-php-client][download][type] = "git"
libraries[google-api-php-client][download][url] = "https://github.com/google/google-api-php-client.git"
libraries[google-api-php-client][revision] ="5ae905585754ef2571ba5ff7ab69a4d624edde90"
libraries[google-api-php-client][directory_name] = "google-api-php-client"
libraries[google-api-php-client][type] = "library"

; Spyc library
libraries[spyc][download][type] = "get"
libraries[spyc][download][url] = "https://raw.githubusercontent.com/mustangostang/spyc/master/Spyc.php"
libraries[spyc][directory_name] = "spyc"
libraries[spyc][type] = "library"

; Superfish
libraries[superfish][download][type] = "git"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal.git"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; TinyMCE
libraries[tinymce][download][type] = "git"
libraries[tinymce][download][url] = "https://github.com/tinymce/tinymce.git"
libraries[tinymce][download][tag] = "3.3rc1"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

